/** Shared catalogue vocabulary used by the marketplace parser and ability filters. */
export const MCP_MAIN_CATEGORIES = [
	"ai-agents",
	"automation",
	"cad-3d",
	"communication",
	"creative-media",
	"data-databases",
	"developer-tools",
	"knowledge-memory",
	"productivity",
	"system-tools",
	"web-search",
	"uncategorized",
] as const;

export const MCP_FEATURE_TAGS = [
	"3d-modeling",
	"ai",
	"automation",
	"browser",
	"cad",
	"cloud",
	"communication",
	"data-analysis",
	"database",
	"documents",
	"email",
	"filesystem",
	"finance",
	"image-generation",
	"issue-tracking",
	"memory",
	"maps",
	"search",
	"security",
	"developer-tools",
	"video-generation",
	"blender",
	"freecad",
	"solidworks",
	"git",
] as const;
